appname: "RackerTracker"
layout: "main"
charset: "UTF-8"
serializer: 'JSON'
admin_password: '755'

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
