# configuration file for production environment
# Rename this file to production.yml
# Make sure to update the dsn

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors 
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1

plugins:
  DBIC:
    default:
      schema_class: 'FitnessChallenge::Schema'
      dsn: 'dbi:SQLite:dbname=/var/fitness-challenge/fitness.db'
